
package socket_comunicador;


import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import socket_comunicador.Pessoa;
import socket_comunicador.ThreadEnviadora;
import socket_comunicador.ThreadRecebedora;

/**
 *
 * @author laboratorio
 */

public class IntefaceServidor extends javax.swing.JFrame {
        
    /**
     * Creates new form Frame
     */
    public IntefaceServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Porta = new javax.swing.JTextField();
        btn_Porta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Porta: ");

        txt_Porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PortaActionPerformed(evt);
            }
        });

        btn_Porta.setText("Ligar");
        btn_Porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PortaActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100)
                        .addComponent(txt_Porta, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btn_Porta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Porta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PortaActionPerformed

    }//GEN-LAST:event_txt_PortaActionPerformed

    private void btn_PortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PortaActionPerformed
        int porta = Integer.parseInt(txt_Porta.getText());
        btn_Porta.setEnabled(false);
        txt_Porta.setEnabled(false);

        Thread threadServidor = new Thread() {

            // O método run() desta thread contém TODA a lógica do servidor
            public void run() {
                try {
                    // O ServerSocket é criado aqui dentro
                    ServerSocket servidor = new ServerSocket(porta);
                    System.out.println("Servidor iniciado. Aguardando clientes...");

                    // O loop para aceitar clientes está aqui dentro
                    while (true) {
                        Socket cliente = servidor.accept();
                        System.out.println("Cliente conectado: " + cliente.getInetAddress().getHostAddress());

                        // E a criação das threads de comunicação também está aqui
                        ThreadRecebedora tr = new ThreadRecebedora(cliente);
                        ThreadEnviadora te = new ThreadEnviadora(cliente);
                        tr.start();
                        te.start();
                    }
                } catch (IOException e) {
                    e.printStackTrace(); // <-- Agora sim ele imprime o erro
                }
            }
        };
        threadServidor.start();
    

    }//GEN-LAST:event_btn_PortaActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new IntefaceServidor().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Porta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Porta;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
