/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplo2_gerarEmail;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author laboratorio
 */
public class IntefaceServidor extends javax.swing.JFrame {
    
    /**
     * Creates new form Frame
     */
    public IntefaceServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Porta = new javax.swing.JTextField();
        btn_Porta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Porta: ");

        txt_Porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PortaActionPerformed(evt);
            }
        });

        btn_Porta.setText("Ligar");
        btn_Porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PortaActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100)
                        .addComponent(txt_Porta, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btn_Porta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Porta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PortaActionPerformed
           
    }//GEN-LAST:event_txt_PortaActionPerformed

    private void btn_PortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PortaActionPerformed
          try{
            String porta = txt_Porta.getText();
            int portaSerivdor = Integer.parseInt(porta);
            ServerSocket servidor = new ServerSocket(portaSerivdor);
              System.out.println("Servidor ouvindo a porta:" +porta);
            Socket cliente;
            
            ArrayList<Pessoa> lista = new ArrayList<>();
            Boolean encontrado;
            
            while(true){
                encontrado = false;
                cliente = servidor.accept();
                String enderecoIP = cliente.getInetAddress().getHostAddress();
                
                 int portaCliente = cliente.getPort();
                 
                System.out.println("Cliente conectado no IP: " + enderecoIP);
                System.out.println("Cliente conectado via porta: " + portaCliente);
                
                ObjectInputStream entrada = new ObjectInputStream(cliente.getInputStream());               
                //receber o nome completo do lado do cliente   
                
                String nomePessoa = (String)entrada.readObject();                    
                //gerar o email a partir do nome completo - primeiro.sobrenome@ufn.edu.br
                String vetorNome [] = nomePessoa.split(" ");
                String email = vetorNome[0] + "." + vetorNome[vetorNome.length-1] +
                        "@ufn.edu.br";
                nomePessoa = nomePessoa.toUpperCase();
                
                email = email.toLowerCase();
                //criar um objeto Pessoa(nome, email)
                Pessoa p = new Pessoa(nomePessoa, email);
                
                if (lista.contains(p)) {
                    encontrado = true;                    
                } else {
                    lista.add(p);
                }
                //devolver o objeto criado
                ObjectOutputStream saida = new ObjectOutputStream(cliente.getOutputStream());
                saida.flush();
                if (!encontrado) {
                    saida.writeObject(p);
                } else {
                    saida.writeObject(null);
                }

                saida.close();
                cliente.close();
                System.gc();
                
                StringBuilder textoNome = new StringBuilder();
                textoNome.append("Cliente: ").append(nomePessoa).append("\n");
                txt_area.append(textoNome.toString());
                txt_area.setEditable(false);
                
                StringBuilder textoEmail = new StringBuilder();
                textoEmail.append("Email: ").append(email).append("\n");
                txt_area.append(textoEmail.toString());
                txt_area.setEditable(false);
                
                servidor.close();
                
                System.out.println("Clientes na base....");
                for (Pessoa pessoa : lista) {
                    System.out.println(pessoa);                    
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(IntefaceServidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IntefaceServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntefaceServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntefaceServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntefaceServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntefaceServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntefaceServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Porta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Porta;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
